# SPDX-License-Identifier: GPL-2.0-only

DTC_FLAGS_stm32mp257f += -@
DTC_FLAGS_stm32mp257f-ev1-cm33tdcid-ostl-emmc-overlay += -@ -Wno-chosen_node_is_root

dtb-$(TARGET_ARM32) += \

dtb-$(TARGET_ARM64) += \
	stm32mp257f.dtb \
	stm32mp257f-ev1-cm33tdcid-ostl-emmc-overlay.dtb \
	stm32mp257f-dk-cm33tdcid-ostl-emmc-overlay.dtb
